### ISSUE TITLE
Pillow-based drawing broken with Python 3.11

### ISSUE THREAD

**Issue by marph91** [flopp/py-staticmaps#39]
Traceback:

```
Traceback (most recent call last):
  File "...", line 19, in <module>
    image = context.render_pillow(800, 500)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/anaconda/envs/py311/lib/python3.11/site-packages/staticmaps/context.py", line 153, in render_pillow
    renderer.render_attribution(self._tile_provider.attribution())
  File "/home/martin/anaconda/envs/py311/lib/python3.11/site-packages/staticmaps/pillow_renderer.py", line 100, in render_attribution
    _, th = self.draw().textsize(attribution)
            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

Background: `textsize` was removed. See https://stackoverflow.com/a/77074371/7410886.

**Comment by pamelafox** [comment]
I *believe* this may have been fixed in 0.5.0, but that release isn't on pypi yet:
https://pypi.org/project/py-staticmaps/#history

**Comment by flopp** [comment]
@pamelafox true. Unfortunately, I've lost access to pypi - but I'm in the process of account recovery

**Comment by dc-buettgenbach** [comment]
> @pamelafox true. Unfortunately, I've lost access to pypi - but I'm in the process of account recovery

Any success with this already?

**Comment by Remboooo** [comment]
For anyone looking for a workaround, add this before calling `render_pillow()`:

```
import PIL.ImageDraw

def textsize(self: PIL.ImageDraw.ImageDraw, *args, **kwargs):
    x, y, w, h = self.textbbox((0, 0), *args, **kwargs)
    return w, h

# Monkeypatch fix for https://github.com/flopp/py-staticmaps/issues/39
PIL.ImageDraw.ImageDraw.textsize = textsize
```

**Comment by hparlak** [comment]
> For anyone looking for a workaround, add this before calling `render_pillow()`:
> 
> ```
> import PIL.ImageDraw
> 
> def textsize(self: PIL.ImageDraw.ImageDraw, *args, **kwargs):
>     x, y, w, h = self.textbbox((0, 0), *args, **kwargs)
>     return w, h
> 
> # Monkeypatch fix for https://github.com/flopp/py-staticmaps/issues/39
> PIL.ImageDraw.ImageDraw.textsize = textsize
> ```

Thank you. Thank you very much!

**Comment by arabovs** [comment]
> @pamelafox true. Unfortunately, I've lost access to pypi - but I'm in the process of account recovery

have you recovered your key yet ?

**Comment by im-n1** [comment]
@flopp dude, where is your long-lost key? :) This fix needs to be pushed out.

**Comment by arabovs** [comment]
> [@flopp](https://github.com/flopp) dude, where is your long-lost key? :) This fix needs to be pushed out.

There's a workaround I found on stackoverflow sometime ago:
```
# Monkeypatch fix for https://github.com/flopp/py-staticmaps/issues/39
# py-staticmaps throws an error since Pillow have renamed "textsize" to "textlength"
# code bellow is a temporary fix for this issue until package get a fix in the next version
def textsize(self: PIL.ImageDraw.ImageDraw, *args, **kwargs):
    x, y, w, h = self.textbbox((0, 0), *args, **kwargs)
    return w, h

PIL.ImageDraw.ImageDraw.textsize = textsize
# Monkeypatch fix ends here
```

**Comment by hugovk** [comment]
https://pypi.org/project/py-staticmaps/0.5.0/ is now out!

**Comment by im-n1** [comment]
Soooo ... this issue shoud be closed then?

**Comment by flopp** [comment]
Yes, exactly.
